[package]
name = "ethereum-elc"
version = "0.1.0"
edition = "2021"

[dependencies]
ibc = { version = "0.29.0", default-features = false, features = ["serde"] }
ibc-proto = { version = "0.26.0", default-features = false, features = ["parity-scale-codec", "borsh"] }
serde = { version = "1.0", default-features = false }
prost = { version = "0.11", default-features = false }
displaydoc = { version = "0.2", default-features = false }
bytes = { version = "1.2.1", default-features = false }
tiny-keccak = { version = "1.4" }

lcp-types = { git = "https://github.com/datachainlab/lcp", rev = "v0.1.5", default-features = false }
light-client = { git = "https://github.com/datachainlab/lcp", rev = "v0.1.5", default-features = false, features = ["ibc"] }
light-client-registry = { git = "https://github.com/datachainlab/lcp", rev = "v0.1.5", default-features = false }
commitments = { git = "https://github.com/datachainlab/lcp", rev = "v0.1.5", default-features = false }
validation-context = { git = "https://github.com/datachainlab/lcp", rev = "v0.1.5", default-features = false }

ethereum-ibc = { git = "https://github.com/datachainlab/ethereum-ibc-rs", rev = "v0.0.2", default-features = false }
ethereum-ibc-proto = { git = "https://github.com/datachainlab/ethereum-ibc-rs", rev = "v0.0.2", default-features = false }
